# Khởi tạo mảng

In [19]:
import numpy as np

# Tạo một mảng emty
import numpy as np 
x = np.empty([3,2],dtype=int)
print(x)

#=============================================================================================#
# Tạo 1 mảng 2 chiều 3x4 với các phần tử zero, kiểu dữ liệu int
import numpy as np 
x = np.zeros([3,4],dtype=int)
print(x)


#=============================================================================================#
# Khở tạo một mảng 2 chiều 2x3 voqai các phần tử = 1
b = np.ones([2,3])


#=============================================================================================#
# Khởi tạo ma trận vuông đơn vị 5x5
d = np.eye(5)


#=============================================================================================#
# Khởi tạo một ma trận 3x4 với giá trị ngẫu nhiên
e = np.random.random((3,4))


#=============================================================================================#
# Khởi tạo một ma trận giá trị ngẫu nhiên là integer
# Syntax của hàm như sau: random.randint(low, high=None, size=None, dtype=int)
# Ý nghĩa: tạo một mảng/ma trận với giá trị integer ngẫu nhiên trong khoản LOW-HIGHT

np.random.randint(4, size=10) # Khởi tạo một mảng ngẫu nhiên 10 phần tử với giá trị từ 0-3
np.random.randint(5, 9, size=(3,4)) # Khởi tạo một ma trận 3x4 với giá trị ngẫu nhiên từ 5-8


#=============================================================================================#
# syntax của hàm arange như sau: numpy.arange([start, ]stop, [step, ], dtype=None)
# Khởi tạo một mảng với các giá trị từ 0-9
f = np.arange(10)

# Mảng nhận được sẽ là array([1, 4, 7])
np.arange(start=1, stop=10, step=3)


#=============================================================================================#
# Khởi tạo mảng 1 chiều với 10 phần tử có giá trị từ 1-5
np.linspace(1,5,10)

[[0 0]
 [0 0]
 [0 0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


# Tạo mảng: 1 chiều, 2 chiều, 3 chiều...

In [14]:
import numpy as np

# Tạo mảng 0-Array (mảng 0 chiều, 1 giá trị được gọi là scalar)
arr_0D = np.array(50)


#=============================================================================================#
# Tạo mảng 1-Array
arr_1D = np.array([1, 2, 3, 4, 5])


#=============================================================================================#
# Tạo mảng 2-Array
arr_2D = np.array([
                    [1, 2, 3],
                    [4, 5, 6],
                    [4, 5, 6]])


#=============================================================================================#
# Tạo mảng 3-Array với mỗi chiều là một ma trận 3x4
arr_3D = np.array([
                    [[0, 1, 1,5], [1, 0, 1, 2], [1, 1, 0, 9]],
                    [[0, 1, 1, 3], [1, 0, 1, 8], [1, 1, 0, 7]],
                    [[0, 1, 1, 10], [1, 0, 1, 14], [1, 1, 0, 4]]
                    ])


[[1 2 3]
 [4 5 6]
 [4 5 6]]


# Tạo mảng từ dữ liệu có sẵn
Dữ liệu có sẵn ở đây có thể là list, tuple

In [6]:
# Tạo một mảng từ một dữ liệu đã có sẵn
import numpy as np 

x = [1,2,3] # kiểu dữ liệu list

y = (4,5,6) # kiểu dữ liệu tuple

z = [(1,2,3),(4,5,6)] # Kiểu dữ liệu là 1 list các tuple

q = [[1,2,3],[5,9,4],[9,3,0]] # kiểu dữ liệu là list các list (nested-list)

str = ["Hello","world!"] # Kiểu dữ liệu là 1 list các string

a = np.asarray(q)

print(a)


[[1 2 3]
 [5 9 4]
 [9 3 0]]


# Kiểm tra chiều của mảng

In [5]:
# chúng ta dùng method .ndim để kiểm tra chiều của 1 mảng

print(arr_1D.ndim)

1
