# Truy xuất các items trong mảng
Các item trong mảng được đánh số (index)
Dòng của ma trận được đánh số từ trên xuống, bắt đầu = 0
Cột của ma trận được đánh số từ trái qua phải, bắt đầu = 0

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4])

# Xuất ra phần tử thứ 1 trong mảng
print(arr[1]) 

# Xuất ra 2 phần tử đầu tiên của mảng
print(arr[:2])

# Xuất ra các phần tử từ phần tử thứ 1 đến hết mảng
print(arr[1:])

# Xuất ra 2 phần tử cuối của mảng
print(arr[-2:])

2
[1 2]
[2 3 4]
[3 4]


In [ ]:
import numpy as np
 
# Khởi tạo numpy array có shape = (3, 4) có giá trị như sau:
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
 
# Sử dụng slicing để tạo numpy array b bằng cách lấy 2 hàng đầu tiên
# và cột 1, 2. Như vậy b sẽ có shape = (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
 
# Một array tạo ra từ slicing sẽ có cùng địa chỉ với array gốc.
# Nếu thay đổi 1 trong 2 thì array còn lại cũng thay đổi.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] ở đây tương đương với a[0, 1]
print(a[0, 1])   # Prints "77"