# Shape attribue
Thuộc tính shape cho chúng ta biết chiều của mảng (số dòng, số cột)
Thuộc tính này còn được dùng để định dạng lại kích thước của mảng.


In [5]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]]) # Mảng 2 chiều (2 dòng, 3 cột)
print (a.shape) # Xuất ra số dòng, số cột của mảng
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [6]:
# Dùng thuộc tính shape để định dạng lại kích thước của mảng a trên
a.shape = (3,2)
print(a.shape)
print(a)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]


# reshape attribute

In [21]:
# Ngoài ra Numpy còn cung cấp function reshape() cũng mới mục đích định dạng lại kích thước của mảng
# cấu trúc câu lệnh khác đôi chút so với thuộc tính shape

a = np.array([[1,2,3],[4,5,6]]) # Mảng 2 chiều (2 dòng, 3 cột)
print (a.shape) # Xuất ra số dòng, số cột của mảng

# Sử dụng function reshape()
b = a.reshape(3,2)
print(b)


(2, 3)
[[1 2]
 [3 4]
 [5 6]]


In [23]:
# Chuyển mảng từ 1 chiều thành 3 chiều
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2) # Định dạng thành 2 mảng con, mỗi mảng con gồm 3 dòng 2 cột

print(newarr) 
print(newarr.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


# ndim attribute
Thuộc tính này dùng để xem chiều của 1 mảng

In [1]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]]) # Mảng 2 chiều (2 dòng, 3 cột)

print(a.ndim) # Xuất ra số chiều của 1 mảng

2


# size attribute
Thuộc tính này dùng để đếm các phần tử có trong mảng hoặc ma trận.

In [3]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]]) # Mảng 2 chiều (2 dòng, 3 cột)

print(a.size) # Xuất ra số chiều của 1 mảng

6


# itemsize attribute
Thuộc tính này dùng để xem độ dài của elements trong mảng

In [12]:
# Ví dụ 1: dtype of array is int8 (1 byte)

import numpy as np 
x = np.array([1,2,3,4,5], dtype = np.int8) 
print (x.itemsize)

#=========================================================================#
# Ví dụ 2: dtype of array is now float32 (4 bytes)

import numpy as np 
x = np.array([1,2,3,4,5], dtype = np.float32) 
print (x.itemsize)

1


# dtypye attribute
Thuộc tính này để xem kiểu dữ liệu của các element trong mảng

In [3]:
# Ví dụ 2: dtype of array is now float32 (4 bytes)

import numpy as np 
x = np.array([1,2,3,4,5]) 
print (x.dtype)

int32


# flattening array

In [6]:
import numpy as np

# Làm phẳng mảng 2 chiều thành 1 chiều
a = np.array([[1, 2, 3], [4, 5, 6]])

a.ravel()

array([1, 2, 3, 4, 5, 6])

In [7]:
print (a)

[[1 2 3]
 [4 5 6]]


# Convert array to list

In [3]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])

a.tolist()

[1, 2, 3, 4, 5, 6]

Link tham khảo
https://scipy-lectures.org/intro/numpy/operations.html#other-operations