# Sorting data in array

In [16]:
import numpy as np

a = np.array([[4, 3, 5], [1, 2, 1]])

# Sắp xếp tăng dần theo hàng
b = np.sort(a,axis=1) # sort mảng a, sau đó gán vào b, thứ tự mảng a không thay đổi

# Sắp xếp tăng dần theo cột
a.sort(axis=0) # Sort trực tiếp trên mảng a, mảng a thay đổi vị trí so với ban đầu

print(a)

[[1 2 1]
 [4 3 5]]


In [23]:
# Sắp xếp mảng theo thứ tự giảm dần

x = np.array([5, 2, 3, 1, 4])

# Cách viết thứ 1, làm thay đổi mảng a ban đầu
x[::-1].sort()

# Cách viết thứ 2, không làm thay đổi mảng a ban đầu
y = np.sort(x)[::-1]

print(y)

[5 4 3 2 1]


In [39]:
# Ví dụ sắp xếp các phần tử là string
import numpy as np
str = np.array(['banana', 'cherry', 'apple'])
print(np.sort(str))

['apple' 'banana' 'cherry']


# Iterating Arrays
Iterating có nghĩa là duyệt qua từng phần tử trong mảng

In [26]:
import numpy as np

a1 = np.array([8, 2, 3,6, 1, 3]) # Mảng 1 chiều
a2 = np.array([[1, 2, 3], [4, 5, 6]]) # Mảng 2 chiều
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) # Mảng 3 chiều

# In ra các phần tử có trong mảng 1 chiều
for x in a1:
    print(x)
    
# In ra từng dòng trong mảng 2 chiều
for x in arr:
    print(x)

# In ra các phần tử trong mảng 2 chiều
for x in a2:
    for y in x:
        print(y)     

# In ra các phần tử trong mảng 3 chiều
for x in a3:
    for y in x:
        for z in y:
            print(z) 

8
2
3
6
1
3


In [38]:
# In tất cả các phần tử trong các scalar element
# Thay vì dùng vòng lặp for để duyệt qua tất scalar, ta dùng funtion ndinter(array)
import numpy as np

a3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(a3):
    print(x) 

1
2
3
4
5
6
7
8


# Joining Arrays

In [43]:
# Nối 2 mảng 1 chiều
import numpy as np
arr1 = np.array([3, 1, 4])
arr2 = np.array([2, 8, 6])

arr = np.concatenate((arr1, arr2))

print(arr) 

[3 1 4 2 8 6]


In [55]:
# Nối 2 mảng nhiều chiều
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1) # nối 2 mảng theo hàng (dòng)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


# Splitting Arrays

In [63]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4) # Splitting thành 4 array khác nhau

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


# Searching Arrays
Tìm vị trí của phần tử muốn tìm kiếm với một điều kiện nào đó

In [67]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4])

# Tìm vị trí của phần tử có giá trị = 4
x = np.where(arr == 4)

# Tìm vị trí của các phần tử có giá trị lẻ
x = np.where(arr%2 == 1)


print(x) 

(array([0, 2, 4], dtype=int64),)
