# Appending element

In [41]:
# Thêm 1 phần tử vào cuối mảng
import numpy as np
arr = np.array([6, 4, 5])

# Thêm vào 1 giá trị
new_arr = np.append(arr,8)
print(new_arr)

#Thêm vào nhiều giá trị cùng lúc
new_arr = np.append(arr,[2,7,10])
print(new_arr)


[6 4 5 8]
[ 6  4  5  2  7 10]


In [46]:
# Thêm giá trị vào mảng 2 chiều
a = np.array([[1, 2, 3], [4, 5, 6]])

new_arr = np.append(a, [[50, 60, 70]], axis = 0)

print(new_arr)


[[ 1  2  3]
 [ 4  5  6]
 [50 60 70]]


# Replacing element

In [9]:
# Muốn thay đổi giá trị ở vị trí nào trong mảng
# ta truy xuất đến vị trí đó và gán vào giá trị mới
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4])

# Thay đổi giá trị của phần tử đầu tiên thành giá trị = 9
arr[0] = 9
print(arr)

[9 2 3 4 5 4 4]


# Inserting new element

In [17]:
# Insert 1 phần tử mới vào 1 vị trí nào đó trong mảng 1 chiều
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4])

# Chèn giá trị 11 vào vị trí thứ 2 trong mảng
new_arr = np.insert(arr,1,11)

print(new_arr)

[ 1 11  2  3  4  5  4  4]


# Deleting a element

In [47]:
import numpy as np
arr = np.array([11, 2, 3, 4, 5, 4, 4])

print(arr)

# Xóa phần tử đầu tiên trong mảng
new_arr = np.delete(arr,0)

print(new_arr)

[11  2  3  4  5  4  4]
[2 3 4 5 4 4]
